### ISSUE TITLE
Show Prev/Next buttons all the time

### ISSUE THREAD

**Issue by jonhewines** [oxyii/react-native-web-swiper#1]
Hi, thanks for the great slider!

Is there a way to make the Prev/Next buttons show all the time? 

I'm working from a design where the Prev button should be shown (at lower opacity) on the first screen of the slider, and the same treatment for the Next button on the last screen.

Is this possible?

**Comment by oxyii** [comment]
@jonhewines Thanks for your report.

You can upgrade lib to `1.10.0` and use new prop `overRangeButtonsOpacity`. See updated README

**Comment by jonhewines** [comment]
That's awesome, thank you @oxyii !

**Comment by Jin-LiuGit** [comment]
how to use this?
thanks

**Comment by Jin-LiuGit** [comment]
why this props removed?
