### ISSUE TITLE
How to off Prev / Next buttons?

### ISSUE THREAD

**Issue by gshoanganh** [oxyii/react-native-web-swiper#10]
Can I off  buttons Prev / Next?

**Comment by oxyii** [comment]
@gshoanganh Yes. `<Swiper buttonsEnabled={false}>`

**Comment by oxyii** [comment]
@gshoanganh If you want to keep dots visible you can fake prev / next buttons text with spaces for now. Something like this `<Swiper prevButtonText=" " nextButtonText=" ">`. I'll review component props soon. "Dots only" can be possible with next major release

**Comment by oxyii** [comment]
I close this issue. @gshoanganh  if it still actual please comment, I'll reopen

**Comment by amit13091992** [comment]
These both solutions are not working on Android.

`<Swiper prevButtonText=" " nextButtonText=" ">`
Or 
`<Swiper prevButtonElement={<View/>} nextButtonElement={<View/>}>`

**Comment by amit13091992** [comment]
I used below property from library and it worked. THANK YOU.
```
controlsProps={{
    prevTitle: 'prev button title',
    nextTitle: 'next button title',
    dotsTouchable: true, {/* touch over dot will make swiper move to rel slide */}
    dotsPos: 'top',
    prevPos: false, {/* hide prev button */}
    nextPos: 'top-right',
    cellsStyle: {
      'top': { padding: 5, backgroundColor: 'rgba(0, 0, 0, .3)' },
      'top-left': { /* any custom placeholder style */ },
    },
    cellsContent: {
      'bottom-right': <AnyComponent /> {/* Additional content in placeholder */}
    }
  }}
```
