### ISSUE TITLE
next and previous button position change

### ISSUE THREAD

**Issue by chayancbnits** [oxyii/react-native-web-swiper#12]
Thanks for uploading this package.
next and previous button position change react-native-web-swiper

![S](https://user-images.githubusercontent.com/51107138/62807837-0fc7c080-bb14-11e9-9f79-d579cab7391c.png)

**Comment by oxyii** [comment]
@chayancbnits thanks for your report. Will you show dots in your case? You can override `controlsWrapperStyle` for now

**Comment by chayancbnits** [comment]
Thanks for the reply to me also I am using "controlsWrapperStyle" when I wrote, "top: 0 " for the arraow button position in the middle of height, for this reason, the inner TouchableOpacity not clickable
![Sc](https://user-images.githubusercontent.com/51107138/62825228-0860ef80-bbc6-11e9-9485-8a633f04a864.png)
.

**Comment by oxyii** [comment]
@chayancbnits `controlsWrapperStyle` must have `height: 0` but `prevButtonStyle` and `nextButtonStyle` must have a height > 0. So, controls wrapper will not overlay other components. This is temporary solution. I hope swiper [will be](https://github.com/react-native-training/react-native-elements/pull/1981) a part of `react-native-elements` soon and with [totally rewrited](https://github.com/react-native-training/react-native-elements/pull/1981/files#diff-1c09190c69a34c82e1949f1c7c08c46b) props

**Comment by chayancbnits** [comment]
@oxyii Thanks, Now it's clickable but I want to center of the height for direction arrows in both  sides


![Screenshot from 2019-08-10 23:59:49](https://user-images.githubusercontent.com/51107138/62825569-a5725700-bbcb-11e9-84e4-623febfe7b01.png)
.

**Comment by oxyii** [comment]
@chayancbnits This is really temporary solution [snack](https://snack.expo.io/@oxyii/swiper-middle-controls)

**Comment by chayancbnits** [comment]
@oxyii Thanks for supporting me, but in browser slider, the next button onClick event is absolutely working but not in android.

**Comment by oxyii** [comment]
@chayancbnits Please wait. I'll make `v2.0` in a few hours

**Comment by chayancbnits** [comment]
@oxyii Thanks for the support, I am waiting for react-native-web-swiper V2.0

**Comment by oxyii** [comment]
@chayancbnits now you can upgrade to `2.0` and use something like this:

```jsx
<Swiper
  controlsProps={{
    prevPos: 'left',
    nextPos: 'right',
    dotsPos: false,
    cellsContent: {
      'bottom-right': (
        <TouchableOpacity>
          <Text>Your Custom Touchable Component</Text>
        </TouchableOpacity>
      )
    }
  }}
>
...
</Swiper>
```
or you can continue to use touchable inside swiper slides

**Comment by oxyii** [comment]
@chayancbnits As I said, props totally rewrited. So, please take a look at updated [README](https://github.com/oxyii/react-native-web-swiper#readme) and see updated [demo](https://snack.expo.io/@oxyii/react-native-web-swiper)
