### ISSUE TITLE
swiper Auto-height depend on text

### ISSUE THREAD

**Issue by chayancbnits** [oxyii/react-native-web-swiper#17]
Could you tell me react-native-web-swiper set minHeight and depend on inner text container?
For Example, small text set minHeight and full height whenever the long text has come.

**Comment by oxyii** [comment]
@chayancbnits As you know, swiper rewritten recently. And yes, `minHeight` added into swiper second (controls) layer. Could you clarify what exactly works out not as expected?

**Comment by oxyii** [comment]
Please let me know if not stale

**Comment by bikashsahucbnits** [comment]
Is there any way to Auto Size the Different slides of the swiper container??
We have two views to show inside the slider which contains dynamic values with different heights.

How to set the Height of the container according to the inner content size?
We have tried with the below solution with **"onLayout"** prop of view but it does not work with Safari Browser. But it works fine in chrome and firefox.

`<View
      style={{
        borderWidth: 1,
        borderColor: Height > 0 ? "#000" : "#fff",
        borderRadius: 6,
        marginBottom: 5,
        height: Height + 10
      }}
    >
      <Swiper ref={swiperRef} controlsEnabled={false} from={0}>
        <TouchableOpacity
          onLayout={event => {
            let { x, y, width, height } = event.nativeEvent.layout;
            setHeight(height);
          }}
          >
...........................
.............
<Content 2/>
</View>`

**Comment by chayancbnits** [comment]
+1

**Comment by chayancbnits** [comment]
> Is there any way to Auto Size the Different slides of the swiper container??
> We have two views to show inside the slider which contains dynamic values with different heights.
> 
> How to set the Height of the container according to the inner content size?
> We have tried with the below solution with **"onLayout"** prop of view but it does not work with Safari Browser. But it works fine in chrome and firefox.
> 
> `<View style={{ borderWidth: 1, borderColor: Height > 0 ? "#000" : "#fff", borderRadius: 6, marginBottom: 5, height: Height + 10 }} > <Swiper ref={swiperRef} controlsEnabled={false} from={0}> <TouchableOpacity onLayout={event => { let { x, y, width, height } = event.nativeEvent.layout; setHeight(height); }} > ........................... ............. <Content 2/> </View>`

+1

**Comment by oxyii** [comment]
@bikashsahucbnits see README ([Dynamic content](https://github.com/oxyii/react-native-web-swiper#dynamic-content))

Snack example for you https://snack.expo.io/HyH73pZoS

**Comment by chayancbnits** [comment]
I want something like this [Custome height each slide](https://snack.expo.io/@chayancbnits/react-native-web-swiper-custome-heigth)(https://snack.expo.io/@chayancbnits/react-native-web-swiper-custome-heigth)

Actually I set minHeight in the main container for the swiper section.
