### ISSUE TITLE
swiper won't update content on state change

### ISSUE THREAD

**Issue by BabakMot** [oxyii/react-native-web-swiper#18]
If you have views in the swiper with state variables, those component won't get updated even when the state changes! This doesn't happen in 1.16 but after 2.0. Any ideas?

**Comment by oxyii** [comment]
@BabakMot Thanks for your report. Please look [here](https://github.com/oxyii/react-native-web-swiper/issues/15#issuecomment-521966549) and please let me know helps it or not.

**Comment by arun537** [comment]
I have a large number of components that needed to be rendered from the state what would I do? the answer above doesn't work for me.
