### ISSUE TITLE
Swipping not working android

### ISSUE THREAD

**Issue by Foskas** [oxyii/react-native-web-swiper#19]
Does the swipe gestures even work on Android ? 

I have this props and it doesn't work
        timeout={10}
        controlsProps={{
            dotsTouchable: true,
            dotsPos: 'top-right',
            prevPos: false,
            nextPos: false,
            dotActiveStyle: { backgroundColor: red },
        }}

Does any one had this problem ?

**Comment by oxyii** [comment]
@Foskas See [snack](https://snack.expo.io/rJHjQenSr) with your props. All works fine

**Comment by Foskas** [comment]
@oxyii I managed to found the issue. It was on my side. My bad. 

There's another issue with the manual swipe. Sometimes it gets stuck in me middle of the swipe as on the attached images. Any clue on this ?

![69449802_726563284458105_5622655937618640896_n](https://user-images.githubusercontent.com/39563017/64332607-c2ccf200-cfcc-11e9-98d1-a45185d3ace6.png)
![69461400_535951406946693_6566495170081062912_n](https://user-images.githubusercontent.com/39563017/64332608-c2ccf200-cfcc-11e9-8ba9-f722da570b18.png)

Btw, good job on this lib.

**Comment by oxyii** [comment]
@Foskas I will not be able to figure out the problem if I do not see the source code. Please open a new Issue. Please attach a minimum code to reproduce this problem. Offhand, I can say one thing: this behavior is theoretically possible if there are touchable elements inside the swiper
