### ISSUE TITLE
Can't able to set the state from inside the swiper.

### ISSUE THREAD

**Issue by SupriyaGo** [oxyii/react-native-web-swiper#23]
Hi 
I was trying to make a Swiper of five pages. each page has images, and when I click on one page/ on image one Continue button will appear on it.

for this, I tried to set my initial state false and then from my button I tried to set id true, but I can't able to do this. 
the state is not getting updated and the button does not appear. 
Please Help.

Code:
`import React from 'react';
import { StyleSheet, Text, View, Image,SafeAreaView, 
    TouchableWithoutFeedback, TouchableOpacity, TouchableHighlight } from 'react-native';

import Swiper from 'react-native-web-swiper';  
    
export default class MaleShapes extends React.Component {
    constructor(props){
    super(props);
        this.state={
                isButtonDisplayed : false,
            }
    }

    render() {
        return (
            <SafeAreaView style={{flex: 1}}>
                <View style={styles.container}>
                    <Text>Test </Text>

                    <Swiper
                controlsEnabled={false}
                onIndexChanged={this.onSwipe}
                minDistanceForAction={0.10}
                > 
                    <View style={styles.slideContainer}>
                         <TouchableWithoutFeedback 
                            onPress={()=>{this.setState({ isButtonDisplayed: true})}}
                             >
                                     <Image 
                                      resizeMode= 'contain'
                                      style={styles.image}
                                      source={require('../src/shape1.png')}/>
                           </TouchableWithoutFeedback> 
                        {
                            this.state.isButtonDisplayed ?

                            <TouchableOpacity 
                            onPress ={ () => {this.setState({ isButtonDisplayed: false})}}
                            style={styles.continueButton}>
                                <Text style={styles.continueText}> Continue </Text>
                            </TouchableOpacity>                                                
                       
                        : null
                        }
                    </View>
                   
                   <View style={styles.slideContainer}>
                        <TouchableWithoutFeedback 
                         onPress={()=>{this.setState({ isButtonDisplayed: true})}}
                         >
                             <Image 
                             resizeMode= 'contain'
                             style={styles.image}
                             source={require('../src/shape2.png')}/>
                        </TouchableWithoutFeedback> 
                        {
                            this.state.isButtonDisplayed ?

                            <TouchableOpacity 
                            onPress ={ () => {this.setState({ isButtonDisplayed: false})}}
                            style={styles.continueButton}>
                                <Text style={styles.continueText}> Continue </Text>
                            </TouchableOpacity>                                                
                       
                        : null
                        }
                    </View>
                          .
                          .
                          . 
                 </Swiper> 
                    

                </View>
            </SafeAreaView>
            )
        }
    }

    const styles = StyleSheet.create({
        container: {
          flex: 1,
          backgroundColor:'#fff',
          justifyContent:'center'
        },
        image:{
            width:'100%',
            height:'90%'
          },
          continueButton:{
            backgroundColor:'#2C3335',
            borderRadius:16,
            paddingVertical:14,
            paddingHorizontal:80,
            position: 'absolute',
            bottom: 120,
            left:70
          },
          continueText:{
            color:"#fff",
              fontSize:22,
          }
    }
    )`

**Comment by oxyii** [comment]
@SupriyaGo Please try [this](https://github.com/oxyii/react-native-web-swiper/issues/15#issuecomment-521966549). I will fix README soon

**Comment by SupriyaGo** [comment]
How to show and hide the button? 
In your example, if I want to do this-
1. I will touch the background and "press me" switch will appear.

**Comment by SupriyaGo** [comment]
I have tried this, but it's not working... please help



import React from "react";
import { Text, TouchableOpacity, View } from "react-native";
import Swiper from "react-native-web-swiper";

export default class HomeScreen extends React.Component {
  constructor(props){
    super(props);
    this.state={
      value:false,
    }
  }
  render() {
    return (
      <View style={{flex:1}}>
        <Swiper>
          <View style={{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#c1c1c1"}}>
          
          <TouchableOpacity onPress={()=>{this.setState({
            value:true
          })}}>
            <Text>Hello</Text>
          </TouchableOpacity>
          
          {
            this.state.value ?
            <DynamicContentSlide />
            : null
          }
          </View>
          <View style={{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(200,20,20,0.3)"}}>
            <Text>Static Slide</Text>
          </View>
          
        </Swiper>
      </View>
    )
  }
}

class DynamicContentSlide extends React.Component {
  constructor(props) {
    super(props);

    this._increment = this._increment.bind(this);

    this.state = {
      anyStateOrProp: 1,
    };
  }
  
  _increment() {
    const { anyStateOrProp } = this.state;
    this.setState({ anyStateOrProp: anyStateOrProp + 1 });
  }

  render() {
    const { anyStateOrProp } = this.state;
    return (
      <View style={{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(20,200,20,0.3)"}}>
        <TouchableOpacity onPress={this._increment}>
          <Text style={{ color: 'blue' }}>PRESS ME {anyStateOrProp}</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

**Comment by oxyii** [comment]
@SupriyaGo Something like [this](https://snack.expo.io/@oxyii/rnws-show-hide-button)?

**Comment by SupriyaGo** [comment]
@oxyii Now it's working. Thank you so much. :)
