### ISSUE TITLE
Custom inactive dot style

### ISSUE THREAD

**Issue by jsbeaudry** [oxyii/react-native-web-swiper#26]
How can i custom the style of my inactive dot?

**Comment by oxyii** [comment]
Added to [README](https://github.com/oxyii/react-native-web-swiper#with-props)

**Comment by SupriyaGo** [comment]
but dotActiveStyle is not working when I am customizing the DotComponent. How to do?

**Comment by oxyii** [comment]
@SupriyaGo What for `dotActiveStyle` if you are using `DotComponent`? DotComponent will be rendered with three props from swiper: `index`, `isActive` (bool) and `onPress` (can be null if dots is not touchable).
So you can render dots as you want
```jsx
<Swiper
  controlsProps={{
    DotComponent: ({ index, isActive, onPress }) => {
      if (isActive) {
        return <Text onPress={onPress}>Your Active Dot {index+1}</Text>;
      }
      return <Text onPress={onPress}>Your Inactive Dot {index+1}</Text>;
    }
  }}
/>
```

About `dotActiveStyle`: see README. It's `react-native-elements` Badge [`badgeStyle`](https://react-native-training.github.io/react-native-elements/docs/badge.html#badgestyle)

**Comment by SupriyaGo** [comment]
@oxyii Thank You. Got it.

**Comment by ranaashu** [comment]
Style inactive dots without DotComponent 
<Swiper
controlsProps={{
  dotProps: { badgeStyle: { backgroundColor: "white"} }
}}
/>
