### ISSUE TITLE
Trying to use useRef to call swiper from elsewhere

### ISSUE THREAD

**Issue by somilmathur** [oxyii/react-native-web-swiper#28]
Where am I supposed to define the const swiperRef? I'm getting "Can't find variable" error.

**Comment by oxyii** [comment]
@somilmathur `useRef` is a part of new **Hooks** API of React lib.
Please read [docs](https://reactjs.org/docs/hooks-reference.html#useref). If you create traditional class-based component then please read [here](https://reactjs.org/docs/refs-and-the-dom.html)
Okay... this is a little example for you: https://snack.expo.io/SyEJQkCYB
