### ISSUE TITLE
add loop and autoplay

### ISSUE THREAD

**Issue by sajadabasi** [oxyii/react-native-web-swiper#3]
add loop and autoplay

**Comment by oxyii** [comment]
@sajadabasi Thanks for your report.

This slider was written for one commercial project... More precisely, it was allocated to a separate library from that project. Loop and autoplay were not needed in project. Okay, I promise to think carefully about this possibility. Let this issue remain open

**Comment by oxyii** [comment]
@sajadabasi Completed. See [updated README](https://github.com/oxyii/react-native-web-swiper#basic) for version `1.11.0`. Good luck!

**Comment by sajadabasi** [comment]
@oxyii oh thank you, that's perfect.
