### ISSUE TITLE
Not working in web 

### ISSUE THREAD

**Issue by arshidkv12** [oxyii/react-native-web-swiper#36]
It is not working in react native web.

**Comment by felix4321** [comment]
For me it's working. Do you have a code example?

**Comment by arshidkv12** [comment]
Please try with 0.61

**Comment by felix4321** [comment]
I am using react-native 0.61.5 in an expo web project - I had to play a bit around -> For example when using a ScrollView it's not rendered...

**Comment by felix4321** [comment]
There is also a working Demo: Hybrid Snack: https://snack.expo.io/@oxyii/react-native-web-swiper

**Comment by arshidkv12** [comment]
I used same code using create-react-app. It is working with
create-react-native-app.

How can I create react native web app for swiper ?

**Comment by oxyii** [comment]
@felix4321 thanks for your answers.

@arshidkv12 did you install [react-native-web](https://github.com/necolas/react-native-web) correctly? Any others components works fine on web for you? May be [this](https://github.com/oxyii/react-native-web-swiper/issues/2#issuecomment-475060133) can help you?

**Comment by arshidkv12** [comment]
Thank you.
It is working for react-native. But not working for react-native-web. How
to install react-native-web?

**Comment by oxyii** [comment]
So this is not a swiper issue. Please follow [RNWeb instructions](https://github.com/necolas/react-native-web#quick-start)

**Comment by oxyii** [comment]
@arshidkv12 And I recommend you to use [expo](https://expo.io) instead pure react-native and RNWeb. See [official react-native docs](https://facebook.github.io/react-native/docs/getting-started). This is a best way to teaching and understanding react-native and supported platforms

**Comment by arshidkv12** [comment]
I already developed in react-native.

**Comment by MahmoudShaeer** [comment]
+++

**Comment by 1280103995** [comment]
Not work in RN v0.64.2(react-native-web: v0.17.1)
