### ISSUE TITLE
Swipe stops inside ScrollView

### ISSUE THREAD

**Issue by Seba34** [oxyii/react-native-web-swiper#4]
The swipe doesnt work well when is inside in ScrollView.
Relevant code
`
<ScrollView style={{flex:1}}>
<View style={{flex:1, height:120, margin:10, marginBottom:0}}>
                    <Swiper
                      index={0}
                    >
                        <View style={{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(20,200,20,0.3)"}}>
                            <Text>Slide 1</Text>
                        </View>
                        <View style={{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(200,20,20,0.3)"}}>
                            <Text>Slide2</Text>
                        </View>
                    </Swiper>
                </View>
</ScrollView>
`
The error is more noticeable in ios

**Comment by oxyii** [comment]
@Seba34 Thanks for your report.

Can you try to reproduce with `1.13.0` ?

**Comment by rogueturnip** [comment]
I've actually noticed this as well using 1.14.0.  It shows the pagination dots but I can't swipe.

**Comment by oxyii** [comment]
@rogueturnip can you create a [snack](https://snack.expo.io) with issue?

**Comment by rogueturnip** [comment]
I tried to get a snack to save but it's as simple as taking the example from the readme and changing the view to a scrollview.
```
      <View flex={1}>
      <ScrollView style={styles.container}>
                <Swiper>
                    <View style={[styles.slideContainer,styles.slide1]}>
                        <Text>Slide 1</Text>
                    </View>
                    <View style={[styles.slideContainer,styles.slide2]}>
                        <Text>Slide 2</Text>
                    </View>
                    <View style={[styles.slideContainer,styles.slide3]}>
                        <Text>Slide 3</Text>
                    </View>
                </Swiper>
      </ScrollView>
      </View>
```

**Comment by oxyii** [comment]
@rogueturnip This is another issue in your case I think. Swiper [works fine](https://snack.expo.io/@oxyii/swiper-in-scrollview) inside ScrollView

**Comment by oxyii** [comment]
@rogueturnip Please open new issue with more detailed info about bug in your case

**Comment by rogueturnip** [comment]
Thanks.  I'll investigate my case some more.
