### ISSUE TITLE
Crash when gesturesEnabled is set to false

### ISSUE THREAD

**Issue by luai-kalkatawi** [oxyii/react-native-web-swiper#40]
I am facing and issue. I have set gesturesEnabled to false but it is crashing with this error 

> 'TypeError: d is not a function. (In 'd()', 'd' is false )'

Need your help @oxyii 

`                                            <Swiper
                            controlsProps={{
                                prevPos: false,
                                nextPos: false,
                            }}
                            gesturesEnabled={false}
                        >`

Regards,

**Comment by dantenol** [comment]
try `gesturesEnabled={() => false}`

**Comment by masroor11** [comment]
> try `gesturesEnabled={() => false}`

Thank you @dantenol ...this works me
