### ISSUE TITLE
Support React-Native version 0.62

### ISSUE THREAD

**Issue by Shing-Ho** [oxyii/react-native-web-swiper#44]
Animated.event now requires a second argument for options 
    in Swiper (at MainView/​index.js:1168)
    in MainView (created by ConnectFunction)
    in ConnectFunction (created by SceneView)
    in SceneView (at StackViewLayout.tsx:900)
    in StackViewLayout (created by withOrientation)
    in withOrientation (at StackView.tsx:104)
    in Transitioner (at StackView.tsx:41)
    in StackView (created by Navigator)
    in Navigator (created by KeyboardAwareNavigator)
    in KeyboardAwareNavigator (created by SceneView)
    in SceneView (created by Drawer)
    in Drawer (created by DrawerView)
    in DrawerView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.js:24)
    in App

Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
    in Swiper (at MainView/​index.js:1168)
    in MainView (created by ConnectFunction)
    in ConnectFunction (created by SceneView)
    in SceneView (at StackViewLayout.tsx:900)
    in StackViewLayout (created by withOrientation)
    in withOrientation (at StackView.tsx:104)
    in Transitioner (at StackView.tsx:41)
    in StackView (created by Navigator)
    in Navigator (created by KeyboardAwareNavigator)
    in KeyboardAwareNavigator (created by SceneView)
    in SceneView (created by Drawer)
    in Drawer (created by DrawerView)
    in DrawerView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.js:24)
    in App

**Comment by dngconsulting** [comment]
Same problem here ...

**Comment by oxyii** [comment]
@dngconsulting @Shing-Ho Please try `2.1.1`
