### ISSUE TITLE
[WEB] Having another onPress handler Component makes swiping absurd

### ISSUE THREAD

**Issue by murtraja** [oxyii/react-native-web-swiper#6]
I have an image swiper implementation wherein upon clicking the image, I hide/show details regarding the image, UI buttons etc.
Now whenever I try to drag this image to go to next one, the image doesn't move until I release the mouse button. Then it follows the mouse (no key is pressed at this time), now when I press the mouse button again, proper behaviour is observed.

Therefore, in order for me to go from one element to another I have to:
  1. Start the drag
  2. Release the mouse button as soon as you start the drag
  3. freely move the mouse, the element will follow the mouse
  4. release the mouse, when done.

**Comment by murtraja** [comment]
I could provide a repro given I have a boiler plate setup. #5

**Comment by oxyii** [comment]
@murtraja  Please share your implementation based on [this](https://codesandbox.io/s/2w5320q4zp) CodeSandbox

**Comment by oxyii** [comment]
@murtraja I think I know what you need ))) Now you can upgrade swiper to `1.14` and use two new event `onAnimationStart` and `onAnimationEnd`. See [updated README](https://github.com/oxyii/react-native-web-swiper#basic) and [example](https://codesandbox.io/s/8k419rw6nj). Let me know if issue is still actual

**Comment by murtraja** [comment]
@oxyii, thank you for your quick response. It turns out that the real culprit here is the Image component.
try this:
https://codesandbox.io/embed/32l96l608q

Try swiping your avatar with the mouse, change directions when you reach the end.
7 out of 10 times, you will experience the absurd behaviour in Firefox but it should work perfectly in Chrome.

If you want me to further debug this by keeping logs somewhere OR if you can help me debug this, then please do so.

**Comment by murtraja** [comment]
So the problem is that when we drag our mouse over the image to swipe it, Firefox thinks that we would like to "grab" the image to paste it somewhere else, when this happens, you cannot swipe, but you can drag the image to other applications

**Comment by oxyii** [comment]
@murtraja if your slides have no clickable components, you can try to cover each slide with a transparent overlay. I cannot do this at the library level, because swiper supports clickable components in slides.

**Comment by murtraja** [comment]
Ohh well, this is a Firefox specific issue https://bugzilla.mozilla.org/show_bug.cgi?id=1439068
@oxyii, I once again thank you for your support.

**Comment by oxyii** [comment]
@murtraja Something like [this](https://codesandbox.io/s/j436zjwq5y). Please remove `backgroundColor` (line 20 in `App.js`) and try to reproduce

**Comment by murtraja** [comment]
@oxyii, the frequency of the bug has indeed decreased by having an overlay. Seems like overscrolling helps in reproducing the issue. 
Thanks again!
