### ISSUE TITLE
TypeError: _reactNative is undefined

### ISSUE THREAD

**Issue by ghmeec** [oxyii/react-native-web-swiper#7]
![Screenshot from 2019-06-06 08-43-57](https://user-images.githubusercontent.com/39438375/59019368-72ac8b00-8837-11e9-845a-4ee86bb30117.png)

Am getting this error,

Am using
expo: 33.0
react-native : 0.59

**Comment by oxyii** [comment]
@ghmeec Please share steps to reproduce. Did you remember to install deps? eg did you install `react-native-web` for web platform support?

**Comment by oxyii** [comment]
@ghmeec Anyway this is not a swiper issue. Your app cannot find react-native. For web platform react-native declarations [forwarded](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L284) to `react-native-web`. Please make sure you have installed `react-native-web` correctly.

**Comment by ghmeec** [comment]
Am using expo which already preconfigured with react native wev,.Thanks for the reply, let me see how am going to customize the settings in expo project.

**Comment by oxyii** [comment]
@ghmeec Ohhh... You are wrong! I noticed that expo merged `expo-web` repo but web platform support is not official yet. And yes, expo did not include `react-native-web` dep! See expo's [package.json](https://github.com/expo/expo/blob/master/packages/expo/package.json)

**Comment by oxyii** [comment]
@ghmeec I changed swiper build settings. Please upgrade swiper to `1.15.1`. Must work ))

**PS** I apologize for not understanding

**Comment by ghmeec** [comment]
thanks for your response.

**Comment by ghmeec** [comment]
![Screenshot from 2019-06-07 09-58-14](https://user-images.githubusercontent.com/39438375/59096679-ebc8e280-890a-11e9-89f5-67536c00f815.png)
finally got it working. Thanks
