### ISSUE TITLE
Nice to be able to disable swiping

### ISSUE THREAD

**Issue by david-saint** [oxyii/react-native-web-swiper#8]
This is just a suggestion.

Sometime we might want to disable swiping until a condition is met.

It should be able to use the buttons but not the swipe.

**Comment by oxyii** [comment]
@david-saint Please use `1.15` with 2 new props: `swipingEnabled` and `buttonsEnabled`. See [updated README](https://github.com/oxyii/react-native-web-swiper#basic)

**Comment by david-saint** [comment]
Nice thanks 🔥🔥🔥🔥🔥🔥🙌🏾🙌🏾🙌🏾
