### ISSUE TITLE
The swiping page is too slow

### ISSUE THREAD

**Issue by iOSUser110** [oxyii/react-native-web-swiper#9]
like its lagging, please suggets me what to change

**Comment by oxyii** [comment]
@iOSUser110 I had slowdowns when I used large SVG as swiper slide content. Can you share code of your case? Or please create a [snack](https://snack.expo.io) better.

**Comment by oxyii** [comment]
Allow to tune `Animated.spring`

**Comment by oxyii** [comment]
Please use `v2.0`
